// src/config/dotenvXConfig.js
const dotEnvX = require('@dotenvx/dotenvx');
dotEnvX.config()
module.exports = {
    
    HOST: process.env.HOST || 'NO ENCONTRE VARIABLE DE ENTORNO',
    PORT: process.env.PORT || 'NO ENCONTRE PORT',
    API_URL: process.env.API_URL || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    // Cassandra
    CASSANDRA_HOST: process.env.CASSANDRA_HOST || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    CASSANDRA_DATACENTER: process.env.CASSANDRA_DATACENTER || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    CASSANDRA_KEYSPACE: process.env.CASSANDRA_KEYSPACE || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    CASSANDRA_USERNAME: process.env.CASSANDRA_USERNAME || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    CASSANDRA_PASSWORD: process.env.CASSANDRA_PASSWORD || 'NO SE ENCONTRO VARIABLE DE ENTORNO',
    // Mongo
    CONNECTION_STRING: process.env.CONNECTION_STRING || 'NO SE ENCONTRO VARIABLE DE ENTORNO', 
    DATABASE: process.env.DATABASE || 'NO SE ENCONTRO VARIABLE DE ENTORNO',  
    DB_USER: process.env.DB_USER || 'NO SE ENCONTRO VARIABLE DE ENTORNO',  
    DB_PASSWORD: process.env.DB_PASSWORD || 'NO SE ENCONTRO VARIABLE DE ENTORNO'
};